feat: upgrade conference app to Ionic 7
ionic-team/ionic-react-conference-app pull request #114
Opened 2023-03-21 19:56 UTC by sean-perkins

This PR updates the React Conference app to the "latest", including Ionic Framework v7, React v18, Vite, Swiper 9 (using Swiper Element) and fixes bugs related to the app.

All changes:
- Added prettier to format the codebase
- Migrated from `react-scripts@3` to `vite`
- Migrated from `react@17` and `react-dom@17` to `react@18` and `react-dom@18`
  - Updated type usage to use `PropsWithChildren` where appropriate
- Migrated from `swiper@7` to `swiper@9`, includes moving to the Swiper Element web component.
  - Adds manual custom types for JSX type support on web component
- Updated outdated links to Github repository
- Updated outdated links to the getting started docs
- Fixed a bug where checkbox inside of filter would not toggle correctly
- Migrated form controls to simplified syntax with `label` and `label-placement`
- Migrated "error" slot content into actual error slot of form control

2023-03-24 19:20 UTC, liamdebeasi reviewed
> Migrated from swiper@7 to swiper@9, includes moving to the Swiper Element web component

The Slides migration guide (https://ionicframework.com/docs/react/slides) recommends sticking with the Swiper React component for now. We might want to hold off on Swiper Element in React until https://github.com/nolimits4web/swiper/issues/6466 is merged.

2023-03-28 15:56 UTC, sean-perkins commented
Updated to use CSS scrolling snapping. Following the style/implementation that is being implemented for the Angular conference app: https://github.com/ionic-team/ionic-conference-app/pull/1790

2023-03-28 19:35 UTC, liamdebeasi requested changes

2023-03-28 19:35 UTC, liamdebeasi commented on package.json
>      "react-router": "^5.2.0",
Can we also update the react router deps to the latest v5? I get the following peer dependency warning:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: mini-create-react-context@0.4.1
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   6 more (@ionic/react, @ionic/react-router, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0" from mini-create-react-context@0.4.1
npm WARN node_modules/react-router/node_modules/mini-create-react-context
npm WARN   mini-create-react-context@"^0.4.0" from react-router@5.2.0
npm WARN   node_modules/react-router
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0" from mini-create-react-context@0.4.1
npm WARN   node_modules/react-router/node_modules/mini-create-react-context
npm WARN     mini-create-react-context@"^0.4.0" from react-router@5.2.0
```

(I had to fix the same issue in the swiper migration repo)

2023-03-28 19:35 UTC, liamdebeasi commented on src/pages/Tutorial.scss
> +    scroll-snap-type: x mandatory;
Can we add `scroll-snap-stop` you can't accidentally swipe over multiple slides: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-stop

2023-03-28 19:35 UTC, liamdebeasi commented on src/pages/SchedulePage.tsx
> +              onIonChange={(e: CustomEvent) => setSearchText(e.detail.value)}
Should this be `onIonInput` now? The search is only going to update on blur

2023-03-28 19:35 UTC, liamdebeasi commented on src/pages/Login.tsx
> +                onIonChange={(e) => setUsername(e.detail.value as string)}
Should this be onIonInput?

2023-03-28 19:35 UTC, liamdebeasi commented on src/pages/Login.tsx
> +                onIonChange={(e) => setPassword(e.detail.value as string)}
Should this be onIonInput?

2023-03-28 19:35 UTC, liamdebeasi commented on src/pages/Support.tsx
> +                onIonChange={(e) => setMessage(e.detail.value!)}
Should this be onIonInput?

2023-03-29 20:06 UTC, brandyscarney requested changes
### Differences from Angular

I noticed that the react conference app behaves differently than the angular version in certain cases. Maybe we can make a tech debt ticket for these if we don't want to update them now? 

`ionic-conference-app` -> shows toast when favoriting
`ionic-react-conference-app` -> shows alert when favoriting

The alert text when you attempt to remove a favorite or add a favorite that already exists is also different:

![Frame 1](https://user-images.githubusercontent.com/6577830/228653845-747d3e3a-d00d-453e-af37-a69c0799bd1d.png)

It also does not [close the open sliding item](https://github.com/ionic-team/ionic-conference-app/blob/5ad793c582221fc8f4f2ea7a7dbf4788710798a3/src/app/pages/schedule/schedule.ts#L49) when switching between all & favorites.

### Login Bugs

When logging in (Login page) after I enter name & password and click "Login" it tells me "Password is required" until I press login again. I think this is related to the `ionChange` Liam mentioned. Support & Signup do the same thing. 

The app is continuously freezing when I click on Logout:

<img width="1512" alt="Screenshot 2023-03-29 at 3 47 35 PM" src="https://user-images.githubusercontent.com/6577830/228654801-8c21e34d-e8c5-497b-95d6-cbca9ea1a7b9.png">

I have to kill the tab and open a new one, refresh doesn't work.

2023-03-30 02:23 UTC, sean-perkins commented
Ok - I addressed all of the requested changes and differences in behavior we've acknowledge so far with the React and Angular conference apps (there is likely more).

2023-03-30 14:10 UTC, brandyscarney requested changes

2023-03-30 14:10 UTC, brandyscarney commented on src/pages/Signup.tsx
> +                onIonChange={(e) => {
```suggestion
                onIonInput={(e) => {
```

2023-03-30 14:10 UTC, brandyscarney commented on src/pages/Signup.tsx
> +                onIonChange={(e) => {
```suggestion
                onIonInput={(e) => {
```

2023-03-30 14:11 UTC, brandyscarney commented
All the fixes look good! Just found two missed `ionChange` events on the signup page.

2023-03-30 15:22 UTC, sean-perkins commented
Thank you for catching that!

2023-03-30 19:04 UTC, liamdebeasi approved these changes

2023-03-31 02:46 UTC, merged